# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de6b593a09be2e1bb7b5c29af5731cafa5404bcd3f707b02eaa2185366494aaf42b0f74ed077e65afe8e48d97568feefa83cac4c2e5ea2199164be1967f5eb05

test:
  secret_key_base: 866e4252ef54a19eb92090ee4781dd4d4fb33125c7071bb5a9acd5ba67507ed8255424408da61727607248911678ad38292cb2126f8893ccf3f8d40cecef62f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
